# Generated by Django 4.0.3 on 2022-04-10 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpd_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='job',
            name='strategy',
        ),
        migrations.AddField(
            model_name='job',
            name='gamma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='job',
            name='phi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='job',
            name='qpu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='theta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
