# Generated by Django 4.0.3 on 2022-04-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpd_api', '0003_remove_job_id_job_jobid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='jobid',
            new_name='id',
        ),
    ]
